"""create tags table

Revision ID: 083e10beae78
Revises: 6191340581b7
Create Date: 2026-03-12 17:34:39.604407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083e10beae78'
down_revision: Union[str, Sequence[str], None] = '6191340581b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('season', 'occasion', 'time_of_day', 'weather', 'location_type', 'accord', 'note')", name='ck_tags_type_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'name', name='uq_tags_type_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
