"""create collection items table

Revision ID: 65f9ce846e3b
Revises: f6a84c4739a5
Create Date: 2026-03-12 19:34:09.057568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f9ce846e3b'
down_revision: Union[str, Sequence[str], None] = 'f6a84c4739a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fragrance_id', sa.Integer(), nullable=False),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('ml_remaining', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ownership_type IN ('full_bottle', 'decant', 'sample')", name='ck_collection_ownership_type_valid'),
    sa.CheckConstraint('ml_remaining IS NULL OR ml_remaining >= 0', name='ck_collection_ml_remaining_positive'),
    sa.CheckConstraint('personal_rating IS NULL OR personal_rating BETWEEN 1 AND 10', name='ck_collection_personal_rating_range'),
    sa.CheckConstraint('times_worn >= 0', name='ck_collection_times_worn_positive'),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='uq_collection_user_fragrance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_items')
    # ### end Alembic commands ###
