// Maps "Brand::Name" to a local static image path under /images/
const images: Record<string, string> = {
  'Hugo Boss::Boss Reversed': '/images/boss-reversed.png',
  'Dior::Homme': '/images/homme-2020.png',
  'Dior::Dior Homme': '/images/homme-2020.png',
  'Dolce & Gabbana::The One': '/images/the-one-edt.png',
  'Dolce & Gabbana::The One for Men': '/images/the-one-edt.png',
  'Versace::Eros Flame': '/images/eros-flame.png',
  'Guerlain::L\'Homme Idéal': '/images/lhomme-ideal.png',
  'Bvlgari::Man in Black': '/images/man-in-black.png',
  'Prada::L\'Homme Prada': '/images/prada-lhomme.png',
  'Giorgio Armani::Acqua di Giò Profondo': '/images/adg-profondo.png',
  'Carolina Herrera::212 Men': '/images/212-men.png',
  'Versace::Man Eau Fraîche': '/images/eau-fraiche-versace.png',
  'Acqua di Parma::Fico di Amalfi': '/images/fico-di-amalfi.png',
  'Moschino::Toy Boy': '/images/toy-boy.png',
  'Ferragamo::Intense Leather': '/images/intense-leather.png',
  'Carolina Herrera::CH Men': '/images/ch-men.png',
  'Givenchy::Gentleman Eau de Toilette Intense': '/images/gentleman-edt-intense.png',
  'Dior::Sauvage': '/images/dior-sauvage.png',
  'Yves Saint Laurent::Y EDP': '/images/y-edp.png',
  'Armaf::Club de Nuit Iconic': '/images/cdn-iconic.png',
  'Montblanc::Legend': '/images/legend.png',
  'Ferragamo::Acqua Essenziale Blu': '/images/acqua-e-blu.png',
  'Abercrombie & Fitch::Fierce': '/images/fierce.png',
  'Rasasi::Hawas for Him': '/images/hawas.png',
  'Maison Alhambra::Jean Lowe Immortal': '/images/immortal.png',
  'Clinique::Happy for Men': '/images/happy.png',
  'Nautica::Voyage': '/images/voyage.png',
  'Perry Ellis::360° Red for Men': '/images/360-red.png',
  'Zara::Sunrise on the Red Sand Dunes': '/images/red-sand-dunes.png',
  'Abercrombie & Fitch::First Instinct Blue': '/images/f-i-blue.png',
  'El Ganso::Bravo Monsieur': '/images/bravo-monsieur.png',
  'Ferragamo::F Black': '/images/f-black.png',
  'Gucci::Guilty Absolute': '/images/guilty-absolute.png',
  'Paris Hilton::for Men': '/images/paris-hilton-for-men.png',
  'Montblanc::Individuel': '/images/individuel.png',
  'Davidoff::Cool Water': '/images/coolwater.png',
  'Burberry::London for Men': '/images/london.png',
  'Adolfo Domínguez::Agua de Bambú': '/images/agua-de-bambu.png',
  'Marc Jacobs::Daisy': '/images/daisy.png',
  'Lancôme::Miracle': '/images/miracle.png',
  'Louis Vuitton::Nouveau Monde': '/images/nouveau-monde.png',
  'Louis Vuitton::Les Sables Roses': '/images/les-sables-roses.png',
  'Jean Paul Gaultier::Scandal Pour Homme': '/images/scandal.png',
  'Givenchy::Gentleman Society': '/images/gentleman.png',
  'Creed::Aventus Absolu': '/images/aventus-absolu.png',
}

export function getFragranceImage(brand: string, name: string): string | null {
  return images[`${brand}::${name}`] ?? null
}
